### ISSUE TITLE
Support accented characters in application name

### ISSUE THREAD

**Issue by qkdreyer** [blakgeek/cordova-plugin-cocoapods-support#17]
FWIK, either Apple Xcode or Cordova while building the xcodeproj file is re-encoding characters such as "é" with "e´".

A quick fix for my case would be replacing
```
var appName = configParser.name();
```
with :
```
var appName = configParser.name().replace("\u00E9", "\u0065\u0301");
```

Looks the same, but different :
```
console.log("\u00E9", "\u0065\u0301", "\u00E9" === "\u0065\u0301")
é é false
```

Are you aware of this issue ?

**Comment by guirip** [comment]
Hello @qkdreyer (salut ;-))

I encountered the exact same issue this morning, but this was before using this plugin so I assume it is related to Cocoa Pods itself.

Cheers!
