### ISSUE TITLE
Bad platform version

### ISSUE THREAD

**Issue by guirip** [blakgeek/cordova-plugin-cocoapods-support#18]
Hello

Thanks for the plugin, struggled this summer while using Cocoa Pods with Cordova (a real PITA) so I really enjoy your work which allows a cleaner build script.

However I lost few hours today figuring out why I couldn't install the cocoa dependencies (not being an iOS developer wasn't helping). Finally I noticed this :
- config.xml contains the entry `deployment-target` specifying `8.0`
- the generated XCode project properly uses this value and defines its `Deployment Target` value to `8.0`
- but the Podfile contains: `platform :ios, '7.0'`

I am using the 1.2.10 release.

Easy to reproduce:
- `cordova platform rm ios`
- `cordova plugin rm cordova-plugin-cocoapod-support` (--force if needed)
- `cordova plugin add cordova-plugin-cocoapod-support`
- `cordova platform add ios`

Same result
- config.xml defines `8.0`
- XCode project says `8.0`
- Podfile containes `7.0`

**Comment by guirip** [comment]
Ok, I realized that your plugin adds specific properties :

plugin.xml:
`<pods-config ios-min-version="9.0" uses-frameworks="true"/>`

config.xml:
`<preference name="pods_ios_min_version" value="8.0"/>`

It feels to me like duplicating the cordova property `deployment-target` ([doc](https://cordova.apache.org/docs/en/latest/config_ref/)).

**Comment by blakgeek** [comment]
@guirip You're right.  I didn't realized there was already a deployment-target preference.  I'll deprecate pods_ios_min_version and support using the value in deployment-target.
