### ISSUE TITLE
Extended ReadMe for Newbs

### ISSUE THREAD

**Issue by gotoAndBliss** [blakgeek/cordova-plugin-cocoapods-support#29]
Hey @blakgeek ! Awesome work!

I'm having a little trouble understanding the ReadMe. I'm trying to make a CocoaPod from this git 

https://github.com/Kandy-IO/kandy-phonegap

And I edited the plugin.xml config as so :

```
    <!-- iOS -->
    <platform name="ios">
        <pods-config ios-min-version="9.0" use-frameworks="true"/>
        <pod id="kandy-phonegap" git="https://github.com/Kandy-IO/kandy-phonegap.git" configuration="release,debug" />
```

And in my config.xml :

```
        <preference name="pods_use_frameworks" value="true"/>
        <pod id="kandy-phonegap" git="https://github.com/Kandy-IO/kandy-phonegap.git" configuration="release,debug" />
```

But I get this error : 

` Unable to find a specification for 'kandy-phonegap'.`

I also see it accessible as a Pod here :  https://cocoapods.org/pods/Kandy

Any advice for a daft cocoa newbie? I'd be more than happy to fork more clearer directions to the ReadMe

**Comment by blakgeek** [comment]
@gotoAndBliss You are trying to add a pod dependency on the Cordova plugin not the cocoapod.

Try changing the entry in your config.xml from
```
<pod id="kandy-phonegap" git="https://github.com/Kandy-IO/kandy-phonegap.git" configuration="release,debug" />
```
to
```
<pod id="Kandy" configuration="release,debug" />
```

There's no need to modify the plugin.xml unless you forked the plugin.
