### ISSUE TITLE
uses-frameworks="true" in plugin.xml doesnt set use_frameworks! in Podfile

### ISSUE THREAD

**Issue by djett41** [blakgeek/cordova-plugin-cocoapods-support#32]
I have a plugin that includes this plugin as a dependency and configures a few pods.  In the plugin I use the following configuration

```
        <dependency id="cordova-plugin-cocoapod-support" version="1.2.14" />

        <pods-config ios-min-version="8.0" uses-frameworks="true"/>    
        <pod id="GoogleConversionTracking" version="3.4.0"/>
        <pod id="FirebaseAppIndexing" version="1.0.3"/>
```

However, when I rm and add the ios platform, the Podfile does not have use_frameworks! in Podfile.  If I also add the preference     <preference name="pods_use_frameworks" value="true"/>
in the project that uses the plugin, then use_frameworks! is added to the Podfile, however I would expect the plugin config to take care of that so users who use the plugin dont have to add this in their project.

**Comment by djett41** [comment]
oops... typo... use-frameworks not uses-frameworks. my bad case closed!

**Comment by rorystandley** [comment]
Did you find a solution to this?
