### ISSUE TITLE
Plugin won't install successfully

### ISSUE THREAD

**Issue by xatshepsut** [blakgeek/cordova-plugin-cocoapods-support#34]
Running "cordova plugin add cordova-plugin-cocoapod-support" gives following error log

> 
> _Fetching plugin "cordova-plugin-cocoapod-support@~1.3.0" via npm
> Installing "cordova-plugin-cocoapod-support" for ios
> node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v46-darwin-x64.tar.gz
> node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v46-darwin-x64.tar.gz
> node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v46-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@4.4.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
> node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v46-darwin-x64.tar.gz 
> In file included from ../vendor/libxml/xpath.c:476:
> ../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity' [-Wunused-function]
> trio_is_special_quantity
> ^
> ../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative' [-Wunused-function]
> trio_is_negative
> ^
> 2 warnings generated.
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9_
> 

https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v46-darwin-x64.tar.gz file does not exist physically.

OS: macOS 10.12.3
Cordova: 6.4.0

**Comment by nevech** [comment]
I have the same problem.

```
Installing "cordova-plugin-awscognito" for ios
Fetching plugin "cordova-plugin-cocoapod-support" via npm
Installing "cordova-plugin-cocoapod-support" for ios
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@6.9.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz 
In file included from ../vendor/libxml/xpath.c:476:
../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity' [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative' [-Wunused-function]
trio_is_negative
^
2 warnings generated.
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
```

OS: macOS 10.12.3
Cordova: 6.5.0

**Comment by chendo** [comment]
I've run into this problem. Current workaround is to run `cordova prepare ios` again. Plugin appears to have still installed fine, it seems it's just the hook isn't working properly.
