### ISSUE TITLE
lib isn't installed

### ISSUE THREAD

**Issue by sanasark** [blakgeek/cordova-plugin-cocoapods-support#39]
hello,
i develop my custom plugin and in plugin xml i use following code 
````
<platform name="ios">

        <dependency id="cordova-plugin-cocoapod-support"/>
 <dependency id="cordova-plugin-add-swift-support" version="1.6.1"/>

<pods-config ios-min-version="9.0" use-frameworks="true"/>

<pod id="Firebase/Core" version = "4.0.3" />



</platform>
````
when i add plugin everything goes fine but in the pod file Firebase/Core didn't present and also wasn't installed in project

**Comment by blakgeek** [comment]
Can you post a gist of the output from ```cordova prepare --verbose```?
