### ISSUE TITLE
Plugin is broken using cordova cli 9.0.0

### ISSUE THREAD

**Issue by EmeryGuillaume** [blakgeek/cordova-plugin-cocoapods-support#47]
Using the latest cordova cli version, this plugin prevents the project to build.
```
cordova create test
cd test
cordova platform add ios
cordova build ios
```
> So far, the build is successful
```
cordova plugin add cordova-plugin-cocoapod-support
cordova build ios
```
> The project doesn't build and here is the output:

`Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

The method requireCordovaModule is used in podify.js. This method has been deprecated (see: https://github.com/apache/cordova-lib/pull/707)

**Comment by rafaismyname** [comment]
For anyone facing this issue, adding @EmeryGuillaume 's fork solves the problem:

`cordova plugin add https://github.com/EmeryGuillaume/cordova-plugin-cocoapods-support.git`

thanks @EmeryGuillaume!

**Comment by davidachin** [comment]
@blakgeek It looks like the fix was added but there hasn't been a release/tag. Do you mind creating a 1.6.1?
