### ISSUE TITLE
Preferences pods_ios_min_version not recognized

### ISSUE THREAD

**Issue by Stending** [blakgeek/cordova-plugin-cocoapods-support#7]
Hi,
I need to fix the ios min version to 9.0 for my cordova plugin, but when I simply add `<preference name="pods_ios_min_version" value="9.0"/>`, in my plugin.xml, I just get an error during the plugin's installation : 

> Error: Variable(s) missing: PODS_IOS_MIN_VERSION

It looks like cordova doesn't accept a preference he doesn't know...

**Comment by blakgeek** [comment]
That preference isn't currently supported at the plugin level.  It can only be set in the project's config.xml.

**Comment by blakgeek** [comment]
I need to fix the documentation.

**Comment by blakgeek** [comment]
@Stending This now supported in plugin.xml with the latest release (>=1.2.9).
